// This file is auto-generated by scripts/generate-help.ts
// Do not edit manually — edit JSDoc in the source file instead

import type { CommandHelp } from "../help.js";

export const corpusDescription: string = "KDTree corpus for nearest-neighbor resynthesis";

export const corpusCommands: CommandHelp[] = [
  {
    name: "build",
    signature: "corpus.build(source?, featureHashOverride?)",
    summary: "Build a KDTree from onset slices of an audio file",
    description: `Build a KDTree corpus from the onset slices of an audio file.
Requires sample.onsets() and sample.slice() to have been run first.
If source is omitted, uses the currently loaded audio.`,
    params: [
      { name: "source", type: "string | Sample | PromiseLike<Sample>", description: "Audio source. Omit to use current audio.", optional: true },
      { name: "featureHashOverride", type: "string", description: "Override the feature hash (advanced use).", optional: true },
    ],
    examples: [
      "const samp = sn.read('loop.wav')\\ncorpus.build(samp)",
      "corpus.build()",
    ],
  },
  {
    name: "query",
    signature: "corpus.query(segmentIndex, k?)",
    summary: "Find k nearest corpus neighbors for a segment",
    description: `Find the k nearest corpus segments to the segment at segmentIndex.
Returns a ranked table of indices and distances.
k defaults to 5.`,
    params: [
      { name: "segmentIndex", type: "number", description: "Index of the query segment." },
      { name: "k", type: "unknown", description: "Number of nearest neighbors to return. Defaults to 5.", optional: true },
    ],
    examples: [
      "corpus.query(0)",
      "corpus.query(0, 10)",
    ],
  },
  {
    name: "resynthesize",
    signature: "corpus.resynthesize(queryIndices)",
    summary: "Concatenate and play corpus segments by index array",
    description: `Concatenate corpus segments specified by index and play them back immediately.
Useful for auditioning nearest-neighbor query results.`,
    params: [
      { name: "queryIndices", type: "number[]", description: "Array of segment indices to concatenate and play." },
    ],
    examples: [
      "corpus.resynthesize([0, 3, 7, 2])",
      "// Full workflow:\\nconst samp = sn.read('loop.wav')\\nsamp.onsets()\\nsamp.slice()\\ncorpus.build(samp)\\ncorpus.query(0, 5)\\ncorpus.resynthesize([0, 3, 7])",
    ],
  },
];
