// This file is auto-generated by scripts/generate-help.ts
// Do not edit manually — edit JSDoc in the source file instead

import type { CommandHelp } from "../help.js";

export const envCommands: CommandHelp[] = [
  {
    name: "vars",
    signature: "env.vars()",
    summary: "List user-defined variables in scope",
    description: `List user-defined bindings that persist across REPL evaluations.
Each entry shows a name, runtime type label, callable flag, and short preview.`,
    examples: [
      "env.vars()",
    ],
  },
  {
    name: "globals",
    signature: "env.globals()",
    summary: "List built-in Bounce globals",
    description: `List Bounce-provided globals exposed in the current REPL session.
Each entry shows a name, runtime type label, callable flag, and short preview.`,
    examples: [
      "env.globals()",
    ],
  },
  {
    name: "inspect",
    signature: "env.inspect(nameOrValue)",
    summary: "Show details for one binding or value",
    description: `Inspect one runtime binding or direct value. If you pass a string that
matches a user variable or Bounce global, Bounce resolves it by name first.`,
    params: [
      { name: "nameOrValue", type: "unknown", description: "Variable name string or a direct value to inspect." },
    ],
    examples: [
      "env.inspect(\"sn\")",
      "env.inspect(\"samp\")",
      "env.inspect(sn.current())",
    ],
  },
  {
    name: "functions",
    signature: "env.functions(nameOrValue?)",
    summary: "List callable members on a value, or all user-defined functions",
    description: `With no argument: list all user-defined functions in scope.
With an argument: list callable members on that value using the same
callable-property rules as tab completion.`,
    params: [
      { name: "nameOrValue", type: "unknown", description: "Value or name to inspect. Omit to list user-defined functions.", optional: true },
    ],
    examples: [
      "env.functions()",
      "env.functions(sn)",
      "env.functions(\"samp\")",
    ],
  },
];
