// This file is auto-generated by scripts/generate-help.ts
// Do not edit manually — edit JSDoc in the source file instead

import type { CommandHelp } from "../help.js";

export const fsDescription: string = "Filesystem utilities";

export const fsCommands: CommandHelp[] = [
  {
    name: "ls",
    signature: "fs.ls(dirPath?)",
    summary: "List directory contents (dotfiles hidden)",
    description: `List the contents of a directory. Dotfiles and hidden entries are
omitted. Use fs.la() to show everything.

Directories are shown in blue; audio files in green.
Output is capped at 200 entries.`,
    params: [
      { name: "dirPath", type: "string", description: "Path (absolute, relative, or ~). Defaults to cwd.", optional: true },
    ],
    examples: [
      "fs.ls()",
      "fs.ls('~/samples')",
      "fs.ls('../other')",
    ],
  },
  {
    name: "la",
    signature: "fs.la(dirPath?)",
    summary: "List directory contents including dotfiles",
    description: "Like fs.ls(), but includes dotfiles and hidden entries.",
    params: [
      { name: "dirPath", type: "string", description: "Path (absolute, relative, or ~). Defaults to cwd.", optional: true },
    ],
    examples: [
      "fs.la()",
      "fs.la('~/samples')",
    ],
  },
  {
    name: "cd",
    signature: "fs.cd(dirPath)",
    summary: "Change working directory (persists across restarts)",
    description: `Change the REPL's current working directory. The new cwd is persisted
to disk and restored on the next app launch. Supports ~ expansion and
relative paths.`,
    params: [
      { name: "dirPath", type: "string", description: "Target directory (absolute, relative, or starting with ~)." },
    ],
    examples: [
      "fs.cd('~/samples')",
      "fs.cd('../other')",
      "fs.cd('/Volumes/SampleDrive')",
    ],
  },
  {
    name: "pwd",
    signature: "fs.pwd()",
    summary: "Print current working directory",
    description: `Print the current working directory. Relative paths in display()
and other commands resolve against this path.`,
    examples: [
      "fs.pwd()",
    ],
  },
  {
    name: "glob",
    signature: "fs.glob(pattern)",
    summary: "Find files matching a glob pattern (e.g. **\\/*.wav)",
    description: `Find files matching a glob pattern relative to the current working
directory. Supports full glob syntax including ** for recursive search.
Returns a sorted string[] of absolute paths and prints each match.`,
    params: [
      { name: "pattern", type: "string", description: "Glob pattern string." },
    ],
    examples: [
      "fs.glob('*.wav')",
      "fs.glob('**\\/*.{wav,flac}')",
      "fs.glob('drums/**\\/*.wav')",
    ],
  },
  {
    name: "walk",
    signature: "fs.walk(dirPath, handler)",
    summary: "Recursively walk a directory; handler fires per entry",
    description: `Recursively walk a directory, calling handler for each entry.
Walk is capped at 10,000 entries.

fs.FileType values: File · Directory · Symlink · BlockDevice
                    CharDevice · FIFO · Socket · Unknown`,
    params: [
      { name: "dirPath", type: "string", description: "Directory to walk (absolute, relative, or ~)." },
      { name: "handler", type: "WalkCatchAll | WalkHandlers", description: "Catch-all callback or handler-map keyed by fs.FileType." },
    ],
    examples: [
      "fs.walk('~/samples', (filePath, type) => {\\n  if (type === fs.FileType.File) return sn.read(filePath);\\n})",
      "fs.walk('~/samples', {\\n  [fs.FileType.File]: (p) => sn.read(p),\\n  [fs.FileType.Directory]: (p) => { console.log(p); },\\n})",
    ],
  },
];
