// This file is auto-generated by scripts/generate-help.ts
// Do not edit manually — edit JSDoc in the source file instead

import type { CommandHelp } from "../help.js";

export const globalCommands: CommandHelp[] = [
  {
    name: "help",
    signature: "help()",
    summary: "Show the organized command reference",
    description: `Show the organized command reference. For detailed usage of a specific
command or object, call its .help() method directly.`,
    examples: [
      "help()",
      "sn.help()",
      "corpus.help()",
    ],
  },
  {
    name: "clear",
    signature: "clear()",
    summary: "Clear the terminal screen",
    examples: [
      "clear()",
    ],
  },
  {
    name: "debug",
    signature: "debug(limit?)",
    summary: "Show recent entries from the SQLite debug log store",
    description: `Show the most recent entries from the SQLite debug log store.
Useful for diagnosing issues with audio processing or IPC.`,
    params: [
      { name: "limit", type: "unknown", description: "Number of entries to show (default 20).", optional: true },
    ],
    examples: [
      "debug()",
      "debug(50)",
    ],
  },
  {
    name: "clearDebug",
    signature: "clearDebug()",
    summary: "Clear all entries from the debug log store",
    examples: [
      "clearDebug()",
    ],
  },
];
