// This file is auto-generated by scripts/generate-help.ts
// Do not edit manually — edit JSDoc in the source file instead

import type { CommandHelp } from "../help.js";

export const instCommands: CommandHelp[] = [
  {
    name: "sampler",
    signature: "inst.sampler(opts)",
    summary: "Create a sampler instrument",
    description: `Create a new sampler instrument. Load samples per MIDI note with
.loadSample(note, sample), then trigger with .noteOn(note) / .noteOff(note).`,
    params: [
      { name: "opts", type: "{ name: string; polyphony?: number }", description: "Instrument options: name (required), polyphony (default 16)." },
    ],
    examples: [
      "keys = inst.sampler({ name: 'keys' })",
      "keys = inst.sampler({ name: 'keys', polyphony: 8 })",
    ],
  },
  {
    name: "granular",
    signature: "inst.granular(opts)",
    summary: "Create a granular synthesis instrument",
    description: `Create a new granular synthesis instrument. Load a source sample with
.load(sample), control texture with .set({ position, grainSize, density, ... }),
and trigger grain streams with .noteOn(note) / .noteOff(note).`,
    params: [
      { name: "opts", type: "{ name: string; polyphony?: number }", description: "Instrument options: name (required), polyphony (default 4)." },
    ],
    examples: [
      "g = inst.granular({ name: 'clouds' })",
      "g.load(sn.read('/path/to/sound.wav'))",
      "g.set({ position: 0.5, grainSize: 80, density: 20 })",
      "g.noteOn(60)",
      "g.noteOff(60)",
    ],
  },
  {
    name: "list",
    signature: "inst.list()",
    summary: "List all instruments in the current session",
    description: "List all instruments defined in the current session, showing name, kind, and sample count.",
    examples: [
      "inst.list()",
    ],
  },
  {
    name: "get",
    signature: "inst.get(name)",
    summary: "Get an instrument by name",
    description: "Retrieve an existing instrument by name. Returns the instrument object with all methods attached.",
    params: [
      { name: "name", type: "string", description: "Instrument name." },
    ],
    examples: [
      "keys = inst.get('keys')",
    ],
  },
];
