// This file is auto-generated by scripts/generate-help.ts
// Do not edit manually — edit JSDoc in the source file instead

import type { CommandHelp } from "../help.js";

export const midiDescription: string = "MIDI recording and playback";

export const midiCommands: CommandHelp[] = [
  {
    name: "devices",
    signature: "midi.devices()",
    summary: "List available MIDI input devices",
    description: "Returns a list of all available MIDI input devices on the system.",
    examples: [
      "midi.devices()",
    ],
  },
  {
    name: "open",
    signature: "midi.open(index)",
    summary: "Open a MIDI input device by index",
    description: `Open the MIDI input device at the given index (from midi.devices()).
Only one device can be open at a time; call midi.close() first if needed.`,
    params: [
      { name: "index", type: "number", description: "Device index from midi.devices()." },
    ],
    examples: [
      "midi.open(0)",
    ],
  },
  {
    name: "close",
    signature: "midi.close()",
    summary: "Close the active MIDI input device",
    description: "Close the currently open MIDI input device.",
    examples: [
      "midi.close()",
    ],
  },
  {
    name: "record",
    signature: "midi.record(inst, opts?)",
    summary: "Start MIDI recording; returns handle or timed sequence",
    description: `Start recording MIDI events from the open input device.
Returns a MidiRecordingHandleResult when no duration is specified — call h.stop() to finish.
Returns a MidiSequencePromise when opts.duration is set, which resolves automatically.`,
    params: [
      { name: "inst", type: "MidiTargetInstrument", description: "Target instrument to associate with the recording." },
      { name: "opts", type: "MidiRecordOptions", description: "Recording options (duration in seconds, name for the saved sequence).", optional: true },
    ],
    returns: "MidiRecordingHandle",
    examples: [
      "const h = midi.record(keys)\\nconst seq = h.stop()\\nseq.play(keys)",
      "// Timed recording:\\nconst seq = midi.record(keys, { duration: 4 })\\nseq.play(keys)",
    ],
  },
  {
    name: "sequences",
    signature: "midi.sequences()",
    summary: "List saved sequences in the current project",
    description: "Returns all MIDI sequences saved in the current project.",
    examples: [
      "midi.sequences()",
    ],
  },
  {
    name: "load",
    signature: "midi.load(filePath)",
    summary: "Import a .mid file as a sequence",
    description: `Import a Standard MIDI File (.mid) and return it as a MidiSequenceResult.
The imported sequence is transient — it is not auto-saved to the project.`,
    params: [
      { name: "filePath", type: "string", description: "Absolute path to the .mid file." },
    ],
    returns: "MidiSequence",
    examples: [
      "midi.load('~/beats/groove.mid')",
    ],
  },
];
