// This file is auto-generated by scripts/generate-help.ts
// Do not edit manually — edit JSDoc in the source file instead

import type { CommandHelp } from "../help.js";

export const mxCommands: CommandHelp[] = [
  {
    name: "ch",
    signature: "mx.ch(n)",
    summary: "Get a ChannelControl for channel n (1–8)",
    description: `Return a ChannelControl for the specified channel. All methods are chainable.
Use .gain()/.pan()/.mute()/.solo()/.attach()/.detach() to configure the channel.

Properties (not commands): mx.preview, mx.master, mx.channels`,
    params: [
      { name: "n", type: "number", description: "Channel index, 1–8." },
    ],
    examples: [
      "mx.ch(1).gain(-6).pan(-0.2)",
      "mx.ch(2).attach(inst).solo()",
    ],
  },
];
