// This file is auto-generated by scripts/generate-help.ts
// Do not edit manually — edit JSDoc in the source file instead

import type { CommandHelp } from "../help.js";

export const patDescription: string = "PatternResult DSL for rhythmic sequencing";

export const patCommands: CommandHelp[] = [
  {
    name: "xox",
    signature: "pat.xox(notation)",
    summary: "Compile an X0X step pattern for live-coding",
    description: `Compile an X0X step-sequencer pattern from a multi-line notation string.
Returns a PatternResult object that can be played with .play(channel).

X0X notation rules:
  Each line:  NOTE = STEPS   (16 non-whitespace step characters)
  NOTE:       c4, c'4 (sharp/flat one semitone up), a4, etc.
  STEPS:      . = rest,  a-z = soft velocity,  A-Z = loud velocity`,
    params: [
      { name: "notation", type: "string", description: "Multi-line X0X notation string." },
    ],
    examples: [
      "pat.xox(`\\n  c4 = a . . . a . . . a . . . a . . .\\n  e4 = . a . . . a . . . a . . . a . .\\n`).play(1)",
    ],
  },
];
