// This file is auto-generated by scripts/generate-help.ts
// Do not edit manually — edit JSDoc in the source file instead

import type { CommandHelp } from "../help.js";

export const projDescription: string = "Manage Bounce projects — create, switch, and list";

export const projCommands: CommandHelp[] = [
  {
    name: "current",
    signature: "proj.current()",
    summary: "Return the active project and its stored counts",
    examples: [
      "proj.current()",
    ],
  },
  {
    name: "list",
    signature: "proj.list()",
    summary: "List all projects with sample, feature, and command counts",
    examples: [
      "proj.list()",
    ],
  },
  {
    name: "load",
    signature: "proj.load(name)",
    summary: "Load a project by name, creating it if needed",
    description: `Load a project by name. If it does not exist, Bounce creates it and
makes it the current project.`,
    params: [
      { name: "name", type: "string", description: "Project name to load or create." },
    ],
    examples: [
      "proj.load(\"drums\")",
    ],
  },
  {
    name: "rm",
    signature: "proj.rm(name)",
    summary: "Remove a project and all its scoped data",
    description: `Remove a project and all samples, features, and command history
stored inside it. The current project cannot be removed.`,
    params: [
      { name: "name", type: "string", description: "Name of the project to remove." },
    ],
    examples: [
      "proj.rm(\"drums\")",
    ],
  },
];
