// This file is auto-generated by scripts/generate-help.ts
// Do not edit manually — edit JSDoc in the source file instead

import type { CommandHelp } from "../help.js";

export const snDescription: string = "Load and play audio samples; entry point for all audio analysis";

export const snCommands: CommandHelp[] = [
  {
    name: "read",
    signature: "sn.read(path)",
    summary: "Load an audio file from disk and return a SampleResult object",
    description: `Load an audio file from disk and return a SampleResult object.
The sample is stored in the project database for future access via sn.load().`,
    params: [
      { name: "path", type: "string", description: "File path (absolute, relative, or ~). Supports WAV, MP3, OGG, FLAC, M4A, AAC, OPUS." },
    ],
    returns: "Sample",
    examples: [
      "const samp = sn.read(\"kick.wav\")",
      "const samp = sn.read(\"samples/loop.flac\")",
    ],
  },
  {
    name: "load",
    signature: "sn.load(hash)",
    summary: "Load a stored sample by hash and return a SampleResult object",
    description: `Load a stored sample by its hash (or hash prefix) and return a SampleResult object.
Use sn.list() to see available sample hashes.`,
    params: [
      { name: "hash", type: "string", description: "Full or prefix hash from sn.list()." },
    ],
    returns: "Sample",
    examples: [
      "const samp = sn.load(\"a1b2c3d4\")",
    ],
  },
  {
    name: "list",
    signature: "sn.list()",
    summary: "List stored samples and features",
    description: "Show all stored samples and features in the database.",
    examples: [
      "sn.list()",
    ],
  },
  {
    name: "current",
    signature: "sn.current()",
    summary: "Return the currently loaded sample, or null",
    description: "Return the currently loaded sample or null if no sample is active.",
    returns: "Sample",
    examples: [
      "const current = sn.current()",
      "current?.help()",
    ],
  },
  {
    name: "stop",
    signature: "sn.stop()",
    summary: "Stop all active sample playback and looping voices",
    examples: [
      "sn.stop()",
    ],
  },
  {
    name: "inputs",
    signature: "sn.inputs()",
    summary: "List available audio input devices",
    description: `List all available audio input devices.
Triggers a microphone permission request on first call.
Use the index shown to open a device with sn.dev(index).`,
    examples: [
      "sn.inputs()",
      "sn.dev(0)",
    ],
  },
  {
    name: "dev",
    signature: "sn.dev(index)",
    summary: "Open an audio input device by index for recording",
    description: `Open an audio input device by index (from sn.inputs()) and return an AudioDeviceResult.
Use AudioDeviceResult.record() to start recording.`,
    params: [
      { name: "index", type: "number", description: "Device index from sn.inputs()." },
    ],
    returns: "AudioDevice",
    examples: [
      "const mic = sn.dev(0)",
      "const h = mic.record(\"take1\")",
      "h.stop()",
      "mic.record(\"take2\", { duration: 5 })",
    ],
  },
];
