// This file is auto-generated by scripts/generate-help.ts
// Do not edit manually — edit JSDoc in the source file instead

import type { CommandHelp } from "../help.js";

export const transportCommands: CommandHelp[] = [
  {
    name: "bpm",
    signature: "transport.bpm(value?)",
    summary: "Get or set BPM (1–400)",
    description: `Get the current BPM when called with no argument, or set a new BPM value.
Value must be between 1 and 400.`,
    params: [
      { name: "value", type: "number", description: "Beats per minute (1–400). Omit to read current BPM.", optional: true },
    ],
    examples: [
      "transport.bpm()",
      "transport.bpm(140)",
    ],
  },
  {
    name: "start",
    signature: "transport.start()",
    summary: "Start the global clock",
    description: `Start the transport clock. Patterns scheduled with .play() will begin
firing on the next bar.`,
    examples: [
      "transport.bpm(120)\\ntransport.start()\\npat.xox(`c4 = a . . . a . . . a . . . a . . .`).play(1)",
    ],
  },
  {
    name: "stop",
    signature: "transport.stop()",
    summary: "Stop the global clock",
    description: `Stop the transport clock. Reports the last bar, beat, and step
position at the time of stopping.`,
    examples: [
      "transport.stop()",
    ],
  },
];
