// This file is auto-generated by scripts/generate-help.ts
// Do not edit manually — edit JSDoc in the source file instead

import type { CommandHelp } from "../help.js";

export const visDescription: string = "Build and manage waveform and analysis visualizations";

export const visCommands: CommandHelp[] = [
  {
    name: "waveform",
    signature: "vis.waveform(sampleOrPromise)",
    summary: "Create a draft VisSceneResult for a sample waveform",
    description: `Create a draft visualization scene rooted in a sample waveform.
Chain .overlay()/.panel()/.title() and call .show() to render it.`,
    params: [
      { name: "sampleOrPromise", type: "SampleResult | PromiseLike<SampleResult>", description: "Resolved SampleResult or SamplePromise to visualize." },
    ],
    examples: [
      "const samp = sn.read(\"loop.wav\")\\nconst scene = vis.waveform(samp)\\nscene.show()",
      "vis.waveform(sn.read(\"kick.wav\")).show()",
    ],
  },
  {
    name: "stack",
    signature: "vis.stack()",
    summary: "Build multiple visualization scenes in one chained expression",
    description: "Create a VisStackResult and add scenes with .waveform(). Call .show() to render all.",
    examples: [
      "vis.stack().waveform(a).waveform(b).show()",
    ],
  },
  {
    name: "list",
    signature: "vis.list()",
    summary: "List currently shown visualization scenes",
    examples: [
      "vis.list()",
    ],
  },
  {
    name: "remove",
    signature: "vis.remove(id)",
    summary: "Remove a shown visualization scene by id",
    params: [
      { name: "id", type: "string", description: "Scene id from vis.list()." },
    ],
    examples: [
      "vis.remove(\"scene-1\")",
    ],
  },
  {
    name: "clear",
    signature: "vis.clear()",
    summary: "Remove all shown visualization scenes",
    examples: [
      "vis.clear()",
    ],
  },
];
